-- [[
-- Global constants that are available in all scripts.
-- ]]

TUTORIAL_DUMMY_AMOUNT = 6

-- Values for sympathy of factions

SYMPATHY_ABHORRED = -5000
SYMPATHY_HATED = -1000
SYMPATHY_DISLIKED = -100
SYMPATHY_RELUCTANT = -10
SYMPATHY_NEUTRAL = 0
SYMPATHY_ONTRIAL = 10
SYMPATHY_LIKED = 100
SYMPATHY_TRUSTED = 500
SYMPATHY_VALUED = 1000
SYMPATHY_HONORED = 5000
