-- [[
-- Global constants that are available in all scripts.
-- ]]

TUTORIAL_DUMMY_AMOUNT = 6

GOLDENFIELDSTAXES = 160

-- Values for reputation of factions
SOLDIER = 0
REBEL = 1

REPUTATION_ABHORRED = -5000
REPUTATION_HATED = -1000
REPUTATION_DISLIKED = -100
REPUTATION_RELUCTANT = -10
REPUTATION_NEUTRAL = 0
REPUTATION_ONTRIAL = 10
REPUTATION_LIKED = 100
REPUTATION_TRUSTED = 500
REPUTATION_VALUED = 1000
REPUTATION_HONORED = 5000
